[build]
  publish = "."

[[redirects]]
  from = "/terms"
  to = "/#terms"
  status = 301

[[redirects]]
  from = "/refund"
  to = "/#refund"
  status = 301

[[redirects]]
  from = "/privacy"
  to = "/#privacy"
  status = 301
